### ISSUE TITLE
Cannot restart after error

### ISSUE THREAD

**Issue by JorritPosthuma** [kaspermarstal/SimpleElastix#2]
Hi!

First of all, thanks a lot for SimpleElastix! It make my life a lot easier!
While developing, I ran in to a few problems, which I'll list here:

After a error (like `"Too many samples map outside moving image buffer"`), it fails when you try to retry (in the current session). It shows the following message: `"ERROR while setting up xout."`.

~~Secondly, I'm using a moving image mask, and when setting `ImageSampler` to `RandomSparseMask`, it gives the error `"do not call this function when no mask is supplied"`.~~

Finally, I have problem setting parameters of parameterMaps inside a parameterMapList, but I will come back to this with a proper example 😊

**Comment by JorritPosthuma** [comment]
Ah, found out that the RandomSparseMask ImageSampler should only be used with a fixed image mask.

**Comment by kaspermarstal** [comment]
Hi Jorrit!

xout is indeed problematic and I am afraid that it is tied to the implementation of elastix itself. xout lives as as a global object outside the elastix namespace and thus is not tied to lifetime of the elastix class. Instead, any open xout buffers have to be closed manually after elastix as run. This wasn't a problem when elastix was an executable because the OS would close these buffers regardless of how the process would exit (as long as it exits). SimpleElastix has to manage these connections manually (read: [I have to hack elastix](https://github.com/kaspermarstal/elastix/commit/f45d5fa591c91a39b34d1a38b31319d1b3816b47)) which is also why we don't use the vanilla elastix version.

It boils down the fact that xout is not closed if SimpleElastix crashes before finishing because that part of the code isn't reached, and instead xout dangles for as long as the host executable is running, e.g. your python session. The error you see is because xout tries to open the same buffers twice. 

Perhaps it is possible to call the xout close code during error handling. Can you weigh in on this @mstaring? Would this be a feasible approach?  

Not being able to assign parameters inside a parameter map list is known issue that is possibly tied to SWIG generated code. I don't know what to do about that :/

**Comment by JorritPosthuma** [comment]
Hi!

Thanks for your fast response! Is it possible to expose the xoutClose, so I can call it when I know there is an error? Or wouldn't that work?

And indeed, not being able to assign parameters inside a parameter map list was my problem, but just getting them and modifying works, so not a real problem 😊

**Comment by kaspermarstal** [comment]
What about this issue? Does fix work?

**Comment by JorritPosthuma** [comment]
I am currently in the middle of rewriting some code 😋, but I'll test it soon!

**Comment by kaspermarstal** [comment]
:+1:

**Comment by JorritPosthuma** [comment]
I'm still receiving the error using transformix (haven't tested elastix), is that right?

**Comment by kaspermarstal** [comment]
Can you send a minimum viable example (a few lines of code and example data) to kaspermarstal@gmail.com so I can test locally?

**Comment by JorritPosthuma** [comment]
Yes, will have to be this weekend or next week. Have to work on another project next couple days :(

**Comment by kaspermarstal** [comment]
Np!

**Comment by JorritPosthuma** [comment]
I've tried it up to 95742637e0ced004c20606c993a713135f506007, and it still fails. But I see you already have a newer version, so it's compiling! 😋

**Comment by JorritPosthuma** [comment]
I'm running it from iPython right now and it crashes after every registration. I'll try to gather some debug info.

**Comment by kaspermarstal** [comment]
If you send me a minimum viable example that reproduces the problem I will take a look!

**Comment by JorritPosthuma** [comment]
Sorry for the delay, but this example fails for me with commit c98a803907bd66682cea0d159c6af65babd4b4de:

```python
import SimpleITK as sitk

def register(fixed, moving):
    selx = sitk.SimpleElastix()
    selx.LogToConsoleOn()

    affine = sitk.GetDefaultParameterMap('affine')
    affine['RequiredRatioOfValidSamples'] = ("0.99",) # Make it fail :P

    plist = sitk.ParameterMapList()
    plist.append(affine)

    selx.SetParameterMap(plist)
    selx.SetFixedImage(fixed)
    selx.SetMovingImage(moving)

    selx.Execute()

fixed = sitk.ReadImage('fixed.nii.gz')
moving = sitk.ReadImage('moving.nii.gz')

try:
    register(fixed, moving)
except Exception as e:
    print e

# This time will fail with xout
try:
    register(fixed, moving)
except Exception as e:
    print e
```

If you want, I can send you the images also?

**Comment by kaspermarstal** [comment]
Yes, please do!

**Comment by JorritPosthuma** [comment]
https://www.dropbox.com/s/bgq4mv9mmisgxl6/fixed.nii.gz?dl=0
https://www.dropbox.com/s/sn9fah3hkmrsfo6/moving.nii.gz?dl=0

**Comment by kaspermarstal** [comment]
Hi Jorrit

I have tested your script with your data and the problem seems to be solved with the new tip of the SimpleElastix branch (dde6134). Let me know if you are still able to reproduce the problem.

**Comment by JorritPosthuma** [comment]
Ran it using https://github.com/kaspermarstal/SimpleElastix/commit/43167de6c39644f04dfdbf01161cf6c75a0f5f24 and the bug is resolved!

Sorry for the long wait!

**Comment by kaspermarstal** [comment]
No problem, glad the issue has been resolved!
