### ISSUE TITLE
Failed to run "hello world" example in python

### ISSUE THREAD

**Issue by Gnimuc** [kaspermarstal/SimpleElastix#45]
I'm new to ITK. After successfully building SimpleElastix, I got the following errors when running the "hello world" example:
```python
Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import SimpleITK as sitk
>>> fixedImage = sitk.ReadImage('fixedImage.nii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 8215, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/simpleitk20151126-61588-18lv2pz/SimpleITK-0.9.0/Code/IO/src/sitkImageReaderBase.cxx:67:
sitk::ERROR: Unable to determine ImageIO reader for "fixedImage.nii"
```
and it seems python can't find `sitk.Elastix` too:
```python
>>> sitk.Elastix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Elastix'
```

I guess the build process is not quite success. How to fix this problem? Any help would be appreciated!

**Comment by kaspermarstal** [comment]
The first issue may simply be SimpleITK not being able to locate the file. Did you start the python session in the same folder as fixedImage.nii resides? Otherwise try to specify the full path. 

As for the second issue, I can only imagine that you are somehow loading the original SimpleITK module and not SimpleElastix. Did you run `sudo python setup.py install` in the `SimpleITK-build/Wrapping/PythonPackage` folder?

**Comment by kaspermarstal** [comment]
Closing issue. Feel free to re-open if you have further questions.

**Comment by franfcunha** [comment]
Hi! I am having the same problem:
'module' object has no attribute 'SimpleElastix'. I did exactly what you said regarding the execution of python setup.py in the SImpleITK-build/Wrapping/PythonPackage folder.
Please help me! It has been very complicated to get started with simple elastix in python :(

**Comment by PertuyF** [comment]
More information needed here.

What are your OS, python version, python distribution?
Do you use an IDE? Do you have the same error if you launch Python from console?

**Comment by franfcunha** [comment]
I am running on Ubuntu.Using Anaconda distribution with Python 3.6, but I
created 2 virtual envs with python 2.7 and 3.4 in order to avoid potential
dependencies problems.
I decided to rebuild the project and i get the following error:

[ 71%] Built target ITKIntegration
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:118: recipe for target
'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/SimpleITK.dir/all'
failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Yes, i use IDE ( SPYDER) and when using Ipython i got the same error.

Thanks


2017-04-07 18:00 GMT+01:00 PertuyF <notifications@github.com>:

**Comment by franfcunha** [comment]
I am running on Ubuntu.Using Anaconda distribution with Python 3.6, but I created 2 virtual envs with python 2.7 and 3.4 in order to avoid potential dependencies problems. 
I decided to rebuild the project and i get the following error:

[ 71%] Built target ITKIntegration
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:118: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Yes, i use IDE ( SPYDER) and when using Ipython i got the same error.

Thanks


2017-04-07 18:00 GMT+01:00 PertuyF <notifications@github.com>:

**Comment by PertuyF** [comment]
@franfcunha Sorry for the delay. Well, I already had issues with conda envs. You need to be sure that:

1. SimpleElastiX version of SimpleITK was installed for the right env, and not just SimpleITK alone (which is available from conda)
2. your Spyder instance uses the right virtual environment

You can try to activate your environment `source activate your_env_name` then call python and try to import SimpleITK. If it doesn't work it is likely that you did not installed the package for this environment, then install and try again.
If it works, get out of python and call Spyder from this env (the command `spyder` usually works), then try importing SimpleITK from within Spyder.

The confusing part with virtual environments is that they represent virtually separate install of python, so you should install each package for all envs from where you want to use it.

**Comment by franfcunha** [comment]
I really appreciate your reply but the problem that I referred in the last email was specifically regarding the building process.
Regarding the use of virtual envs i was able to import simpleitk in python 3.4 but every methods belonging to SimpleElastix can not be used because they are not recognized...
In the last email sent to you I strightly passed the output of the error about the building process of SimpleITK following the docs available but such building process crush at 71% even allowing me to use SimpleITK methods but not simple elastix methods...
Sincerely,
Francisco



No dia 12/04/2017, às 11:28, PertuyF <notifications@github.com> escreveu:

**Comment by kaspermarstal** [comment]
If the build fails, then SimpleElastix is probably not installed (you have to install it manually after the build process is finished) and you are probably loading an existing version of SimpleITK. The ITKIntegration module that your previous message mentions is part of post-build check. That means the Python package did successfully compile (assuming you didnt use multiple makefile jobs, in that case the true error may have occured earlier). Try to step into `build-dir/Wrapping/Python/Packaging` and execute `sudo python setup.py install` if `setup.py` is there. This will override your previous install of SimpleITK with SimpleElastix.

**Comment by franfcunha** [comment]
I am really sorry but your information was not clear to me. How can I
"manually" install SimpleElastix?

Thank you

2017-04-12 15:04 GMT+01:00 Kasper Marstal <notifications@github.com>:

**Comment by franfcunha** [comment]
All this process is becoming really confusing to me. I am not properly an
IT expert... How can I "uninstall" and remove all the makefile jobs done
until now? I would like to try a clear last time become it is becoming
really time consuming to me to install and to be able to use Simple Elastix
:=(

2017-04-19 11:31 GMT+01:00 Francisco Cunha <francisferreiracunha@gmail.com>:

**Comment by kaspermarstal** [comment]
You uninstall by simply removing the build directory. To start from a clean slate, make a new directory and build the project in here. The "manual install" I am referring to is the `sudo python setup.py install` step that you have to execute after the compilation is finished.

**Comment by anewlearner** [comment]
@kaspermarstal  I installed the SimpleElastix following the tutorial(I did run 'sudo python setup.py install'). Everything is OK during the installation. The final output is as follows.
```
Installed /usr/local/lib/python2.7/dist-packages/SimpleElastix-1.0.1rc1.dev331+gd756f-py2.7-linux-x86_64.egg
Processing dependencies for SimpleElastix==1.0.1rc1.dev331+gd756f
Finished processing dependencies for SimpleElastix==1.0.1rc1.dev331+gd756f
```
But I can only import SimpleITK, but can not use SimpleElastix.
I tried to reinstall both SimpleITK and SimpleElastix, but got same results.

**Comment by edwinvarghese4442** [comment]
@kaspermarstal I have a similar problem. First I had installed SimpleITK (did not know about simple Elastix). So I built the Elastix and ran `sudo python setup.py install`  from the python/packaging sub directory. I tried to run import simpleITK and sitk, but throws the error `module 'SimpleITK' has no attribute 'Elastix'` . Then I sudo uninstalled the first SimpleITK  and I ran `sudo python setup.py install` again. It again imports in IDE and but throws the same error. I tried to import `SimpleITK as sitk` in terminal console and now it shows `ImportError: No module named 'SimpleITK'` . Can you please help? Should I rebuild simple elastix? It took me 12+ hours.

**Comment by kaspermarstal** [comment]
You must more information than Segmentation fault. What is the full error log?

**Comment by edwinvarghese4442** [comment]
@kaspermarstal that is the full error log I get. I guess I have to build it again, because while in the first time I built, I had encountered some errors while being built.

**Comment by moralesq** [comment]
I had the same error, i.e., 

`>>> sitk.Elastix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Elastix'`

and I suspected that it was due to a previous installation of SimpleITK. I deleted the old installation: 

`sudo rm -rf /usr/local/lib/python2.7/dist-packages/SimpleITK*`

and then re-ran the installation command 

`sudo python setup.py install`

that fixed the problem.
