### ISSUE TITLE
SuperBuild on Linux fails if build is tried on network drive

### ISSUE THREAD

**Issue by habi** [kaspermarstal/SimpleElastix#67]
I wanted to [SuperBuild SimpleElastix](https://simpleelastix.readthedocs.io/GettingStarted.html#superbuild-on-linux) on Linux.
My preferred drive is a network drive mounted with Samba.
The build fails due to not being able to make a symbolic link.

**Comment by kaspermarstal** [comment]
Can you be a little more specific? Which symbolic link is being make? At which stage in the build process are you seeing this error? Have you tried with sudo?

**Comment by habi** [comment]
Sorry for not including the necessary info.

I'm trying to build on Ubuntu 16.04.1 LTS, the network drive is mounted according to [this](http://askubuntu.com/a/157140).
Shortly before the process fails, I see this line in the output

    ln: failed to create symbolic link '/home/habi/P/Dev/elastix-build/PCRE/share/man/man3/pcre16_assign_jit_stack.3': Operation not supported

It doesn't make a difference if I `make` or `sudo make`. 
Here's are pastebin links to the output of both [`make`](http://pastebin.com/raw/EDX5eNfP) or [`sudo make`](http://pastebin.com/raw/zYwPJ4NS).

**Comment by habi** [comment]
Building in a local directory seems to work.
Except that I now have the same problem as in Issue #43, as can be seen in the screenshots below.
There's no PythonPackage folder and the Python folder does not contain a `setup.py`.

![screenshot from 2017-01-17 09-10-07](https://cloud.githubusercontent.com/assets/1651235/22012532/c4e3914e-dc94-11e6-8c19-73a7b8570855.png)

**Comment by kaspermarstal** [comment]
With the latest release this directory was changed to `${BUILD_DIRECTORY}/SimpleITK-build/Wrapping/Python/Packaging`. Just `c Packaging` and you will find it. I see that the documentation has not been updated to reflect this, and will change it accordingly.

With respect to the symbolic links, there is probably little we can do from CMake, since it is `ln` itself that fails. After a little googling it looks like this can be a permissions issue (http://superuser.com/questions/128716/ubuntu-latest-samba-version-symlinks-no-longer-work-on-share-mounted-in-windo), upgrade issue (http://superuser.com/questions/106470/no-symlinks-allowed-in-smb-share) or something completely different. I suggest you show your favorite sysadmin some love and perhaps he will help you out :)
