### ISSUE TITLE
Simple Elastix not running after build

### ISSUE THREAD

**Issue by TylerCork** [kaspermarstal/SimpleElastix#8]
I finished the build with and I am unable to perform this tutorial. I understand I would have to input two paths instead of the images there, but the error comes before that. A little bit of background info, I am using a Mac OS X 10.10.5 with ipython notebook. Would I need to install SWIG and elastix in the ipython application as well? Here is the error message I am receiving: 

<img width="1140" alt="screen shot 2016-01-25 at 8 50 01 pm" src="https://cloud.githubusercontent.com/assets/16804422/12570423/75e84804-c3a5-11e5-8c44-9185e29f0e09.png">

**Comment by kaspermarstal** [comment]
It looks like there is a previously installed SimpleITK module which is imported instead of SimpleElastix. Can you check that you see `SimpleElastix` and `SimpleTransformix` in the list of methods when you run `dir(SimpleITK)`? If not, did you run `sudo python setup.py install` in the `SimpleITK-build/Wrapping/PythonPackage` directory? 

You do not need to install SWIG and elastix separately, no. 

Let me know how it goes :)

**Comment by TylerCork** [comment]
I uninstalled the module '''Simple ITK''' and '''SimpleElastix''' from my machine. I then reran the build and I appear to run into a problem when trying to run the python packaging. It doesn't appear to be in the location it should but, but it is in the '''SimpleElastix''' folder that was cloned from github.

![screen shot 2016-01-26 at 9 54 20 am](https://cloud.githubusercontent.com/assets/16804422/12583881/d7b2cb00-c412-11e5-82cf-c2eb6e465ac3.png)

**Comment by kaspermarstal** [comment]
It looks like `WRAP_PYTHON` has been set to `OFF` (there seems to be no `SimpleITKPYTHON_wrap.h` etc). Try to set it to `ON`, restart the build and let me know how it goes :)

**Comment by TylerCork** [comment]
How would I set it to on?

**Comment by kaspermarstal** [comment]
To turn on Python wrapping, go to the top-level build directory, type `ccmake .`, use arrow keys to move the cursor down to `WRAP_PYTHON` and press enter to switch the option to `ON`. It should then look something like this:

<img width="558" alt="screen shot 2016-01-27 at 09 56 20" src="https://cloud.githubusercontent.com/assets/478833/12608436/622419b4-c4dc-11e5-9682-24f169f5d9fc.png">

However, the Python wrapping option should automatically be turned on if Python is available. And it should be available by default because you are on a Mac. So it may be that python is not configured correctly at the moment. But try the steps and above if if it does not work you are welcome to send me your terminal output to kaspermarstal@gmail.com.

**Comment by kaspermarstal** [comment]
I assume your issue was fixed. Please just open the issue again if you still have problems!

**Comment by moralesq** [comment]
I had the same error, i.e., 

`>>> sitk.Elastix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Elastix'`

and I suspected that it was due to a previous installation of SimpleITK. I deleted the old installation: 

`sudo rm -rf /usr/local/lib/python2.7/dist-packages/SimpleITK*`

and then re-ran the installation command 

`sudo python setup.py install`

that fixed the problem.

**Comment by sedghi** [comment]
I had the same problem. I had 3 different versions of SimpleITK. Once I deleted old SimpleITKs then my problem was fixed
