### ISSUE TITLE
TIFF reading... problem

### ISSUE THREAD

**Issue by franfcunha** [kaspermarstal/SimpleElastix#85]
Hi guys,
I am trying to read some .tiff file using sitk.ImageReader, but after a wide search I was not able to figure out what is going wrong here. Here is the error i get:
ReadImage: ..\..\..\..\..\ITK\Modules\IO\TIFF\src\itkTIFFImageIO.cxx:1228: itk::ERROR:TIFFImageIO(0000000008E35880): Problem reading the row: 1036.

I am on Windows 10 btw.
Any ideas?

Thanks in advance!

**Comment by PertuyF** [comment]
Could you post the piece of code that causes the error? Otherwise it's hard to see were it comes from.

Usually `sitk.ReadImage(path_to_your_image)` should work fine for a single image.

**Comment by franfcunha** [comment]
I've just imported SimpleITK as sitk and sitk.ReadImage('path_to_my_tiff_file') using Spyder IDLE

**Comment by PertuyF** [comment]
Are you able to read the image using other software? or another library?

You could try [scikit-image](http://scikit-image.org/):
```python
from skimage.io import imread

img = imread(path_to_your_image)
```
Or test opening with [Fiji](https://fiji.sc/).

**Comment by franfcunha** [comment]
Thank you for your support.
Yes, I can open it easily using Fiji.

2017-03-31 18:40 GMT+01:00 PertuyF <notifications@github.com>:

**Comment by PertuyF** [comment]
And is there anything strange with row 1036? Like abnormal pixel values?

**Comment by franfcunha** [comment]
Not at all. I would like to understand what perhaps could be wrong with my
building installation process. I followed the steps of the docs to build
and instal SimpleITK and i can import it in my IDLE successfully, so I
guess there is no problem on that.
But regarding the modules, the error referes some kind of "exception
thrown" regarding IO TIFF. Does it suggest something to you?

Sorry for the mess...

2017-03-31 18:46 GMT+01:00 PertuyF <notifications@github.com>:

**Comment by PertuyF** [comment]
I never met this error, so I don't have a strong intuition on what's the cause here.

Could you try to install the standard SimpleITK library (not the one built for SimpleElastiX) and try to open again? This would test your idea of something going wrong with your build. I think SimpleITK is available from conda (if you use anaconda) or from pip.

If it doesn't work either you could try to open the image with Fiji, then save it as TIFF and try to open this version from SimpleITK. Just to see.
